/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.ruanvictor

import dev.ruanvictor.config.AppConfig

fun main(args: Array<String>) {
    AppConfig().setup().start(getHerokuAssignedPort())
}

private fun getHerokuAssignedPort(): Int {
    val processBuilder = ProcessBuilder()

    if (processBuilder.environment()["PORT"] != null) {
        return Integer.parseInt(processBuilder.environment()["PORT"])
    }

    return 7000
}
