/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.ruanvictor

import dev.ruanvictor.config.AppConfig

fun main(args: Array<String>) {
    AppConfig().setup().start(7000)
}

